appId: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
server:
  port: 8082
spring:
  application:
    name: lagou-service-email
  cloud:
    config:
      uri: http://127.0.0.1:9006
      name: lagou-service-email
      profile: dev
      label: main
  rabbitmq:
    host: 192.168.160.141
    port: 5672
    username: guest
    password: guest
  mail:
    host: smtp.qq.com
    username: 2570517862@qq.com
    password: xgutipgeiuzcdjei
    protocol: smtp
    default-encoding: UTF-8
    port: 587
eureka:
  instance:
    #服务实例中显示ip，而不是显示主机名（兼容老的eureka版本）
    ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8090/eureka/
    fetch-registry: true
    register-with-eureka: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
